name: Build test with MSVC
on:
  workflow_call:

  # 手動トリガーを許可
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore Nuget Packages
        run: |
          NuGet restore .\Tangband\Tangband.sln

      - name: Run build test
        run: |
          MSBuild -warnAsError .\Hengband\Hengband.sln /t:Rebuild /p:Configuration=Debug
